default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: make_a_post_development

test:
  <<: *default
  database: make_a_post_test

production:
  <<: *default
  database: make_a_post_production
  username: make_a_post
  password: <%= ENV['MAKE_A_POST_DATABASE_PASSWORD'] %>
